"""Added scraped_at column

Revision ID: 2fda81237a86
Revises: 4ff0c8c0ac95
Create Date: 2025-08-24 14:39:11.659524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fda81237a86'
down_revision: Union[str, Sequence[str], None] = '4ff0c8c0ac95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('scraped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'scraped_at')
    # ### end Alembic commands ###
