"""text

Revision ID: 4ff0c8c0ac95
Revises: 6afd2e8ff8c9
Create Date: 2025-08-24 14:28:47.915589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff0c8c0ac95'
down_revision: Union[str, Sequence[str], None] = '6afd2e8ff8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('cars', sa.Column('make', sa.String(length=100), nullable=True))
    op.add_column('cars', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('cars', sa.Column('municipality', sa.String(length=100), nullable=True))
    op.add_column('cars', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.drop_column('cars', 'price_raw')
    op.drop_column('cars', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cars', sa.Column('price_raw', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('cars', 'date_posted')
    op.drop_column('cars', 'municipality')
    op.drop_column('cars', 'model')
    op.drop_column('cars', 'make')
    op.drop_column('cars', 'image_url')
    # ### end Alembic commands ###
