"""modified chat model

Revision ID: d778361335b6
Revises: 56296ab60eda
Create Date: 2025-09-14 11:12:22.766226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd778361335b6'
down_revision: Union[str, Sequence[str], None] = '56296ab60eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('answer', sa.Text(), nullable=True))
    op.alter_column('chats', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('chats', 'answer')
    # ### end Alembic commands ###
